name: Generate Datas

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Adiciona permissão de escrita para o GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v4
      
      # 2. Geração da Animação Snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Elihh2020
          # Define o caminho de saída
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          # Configuração da animação (opcional)
          palette: dracula
          
          
      # 3. Publicação do SVG e GIF gerados
      # A branch 'output' será criada se não existir
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
